### PR TITLE
More Logos.

### PR DESCRIPTION
**Pull request by JamsRepos**
## Description

_Please note, these have not been tested as I am unable to get my development environment running, it's the first time I've used flutter so i'm having quite a few issues._

- Added Channel Island Hosting logo.
- Added Kronos App logo.
- Added Twingate logo.
- Added Revolt logo.
- Added Parsec logo.
- Added Jagex logo.
- Changed Google logo due to clipping issues.
- Changed ngrok logo to be more visible on dark mode.
- Changed Ubisoft logo to be more visible on dark mode.

## Type of Change

- [x] 🖼️ New icon
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by vishnukvmd** [comment]
Hey!

1. We've made colors optional, so for entries like Google, you can remove the hex code, and it will render fine
2. The Termius logo isn't rendering well in dark mode (I'm guessing that's why https://github.com/ente-io/auth/pull/247/commits/d24bc62d1ce176ce4d8c47cb76d4a72263473407 happened)
3. I've introduced the concept of a `slug`, so that for entries like `Channel Island Hosting`, which points to `cih.svg`, you can specify an additional parameter to point to the correct icon
```json
{
  "title": "Channel Island Hosting",
  "slug": "cih",
  "hex": "D14633"
}
```

Thank you! ❤️

**Comment by JamsRepos** [comment]
Yeah, I saw the commit https://github.com/ente-io/auth/commit/d24bc62d1ce176ce4d8c47cb76d4a72263473407 but I didn't want to have all logos the same colour if we could help it of course, I couldn't test to see if that blue would work or not in dark mode, so I left it to you to test, if it doesn't work well then I guess we can just revert that to let the commit mentioned stay in play.

**Comment by JamsRepos** [comment]
Another thing I wanted to mention, seeing as the Jagex logo is a Polygon svg, will the colour still apply or should I leave the colour inside the svg and remove it off the configuration file?

**Comment by vishnukvmd** [comment]
The Jagex is rendering fine, both with and without the explicitly defined color code

**Comment by JamsRepos** [comment]
I've gone ahead and amended the json file to reflect your changes and removed the pre-defined colour code within the SVG to keep some uniformity.

**Review by vishnukvmd — APPROVED** [review]

**Pull request merged**
