### PR TITLE
Add and normalise logos

### PR DESCRIPTION
**Pull request by Eseltwift**
Add Bitwarden, Cloudflare, Notion, Snapchat and NVIDIA logos.
Normalise and update Ubisoft, GitHub and Google logos.

Normalise SVG to 500px × 500px.
Add mix-blend-mode:difference for dark/light mode when needed.

- [x] 🖼️ New icon
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by vishnukvmd** [comment]
Hey, some of these, like Cloudflare are already provided by the `simple-icons` package we're depending on.

Reg. GitHub, iirc the color code was set to ensure visibility in both light and dark modes. Could you please verify that it looks good in both themes?

Thank you!

**Comment by Eseltwift** [comment]
> Hey, some of these, like Cloudflare are already provided by the `simple-icons` package we're depending on.
> 
> Reg. GitHub, iirc the color code was set to ensure visibility in both light and dark modes. Could you please verify that it looks good in both themes?
> 
> Thank you!

Hey there!

I do know some of them are provided by the simple-icons library but they're all monochrome and sometimes not the official logos.
As an Auth user and fussy designer, I like my icons to look perfect. Sometimes it comes down to details like a shift of a few pixels. That's how I see things when I contribute to the project. But feel free to let me know if it's not your vision or ambition for ente Auth.

I'm going to do some tests for icons like GitHub or X, to make sure they're visible in both dark and light mode.

❤️

**Comment by vishnukvmd** [comment]
Thanks for clarifying, we definitely care about every single pixel! ❤️ 

I'll merge the PR once you confirm the visibility of the Github icon.

**Comment by Eseltwift** [comment]
The `mix-blend-mode` works perfectly as you can see. You may merge the PR 👍

image
image

**Review by vishnukvmd — APPROVED** [review]

**Comment by vishnukvmd** [comment]
Hey @Eseltwift, just fyi, the icons for Github and Ubisoft were glitching, so we had to revert them.
Screenshot 2023-10-19 at 11 58 43 AM

**Comment by Eseltwift** [comment]
Hey @vishnukvmd, thanks for letting me know. Weird it did not happen in test environment...
Did you also check for Twitter/X logo ? It is based on the same method.
I'll figure out a solution 😉

**Pull request merged**
