### PR TITLE
Removed: New Qr code analyzing screen and added the old one

### PR DESCRIPTION
**Pull request by i-aiymen**
## Description

Removed the new scanning function implemented and added the old one

## Type of Change

- [ ] 🖼️ New icon
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by i-aiymen** [comment]
@ua741 @vishnukvmd Updated

**Comment by ua741** [comment]
Let's also remove the dependency from pubspec.yaml?

**Comment by i-aiymen** [comment]
> Let's also remove the dependency from pubspec.yaml?

ok

**Comment by i-aiymen** [comment]
@ua741 Updated

**Comment by ua741** [comment]
I realized that's it is simpler to just revert the previous commit as there were other changes also related to indirect dependencies, image picker, & droid sdk requirement changes.

Closing this PR in favor of #354

**Pull request closed without merging**
